name: Deploy to GitHub Pages

on:
  push:
    branches: [ dev ]
  workflow_dispatch:

permissions:
  contents: write
  pages: write
  id-token: write

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout your repository using git
        uses: actions/checkout@v3
        with:
          ref: dev

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18

      - name: Install dependencies
        run: npm install --legacy-peer-deps

      - name: Copy GitHub config
        run: cp astro.config.github.mjs astro.config.mjs

      - name: Build website
        run: npm run build

      - name: Deploy to GitHub Pages branch
        uses: JamesIves/github-pages-deploy-action@v4
        with:
          folder: dist
          branch: master
          clean: true